### ISSUE TITLE
An error for 'pod install'

### ISSUE THREAD

**Issue by bitcwb** [Alfresco/alfresco-ios-app#1176]
When i exec for `pod install`, an error has occurred

> Analyzing dependencies
Cloning spec repo `alfresco` from `https://github.com/Alfresco/alfresco-private-podspecs-ios-sdk`
[!] Unable to add a source with url `https://github.com/Alfresco/alfresco-private-podspecs-ios-sdk` named `alfresco`.
You can try adding it manually in `/Users/chenwenbin/.cocoapods/repos` or via `pod repo add`.

**Comment by emanuellupu** [comment]
Hi, 
Assuming you're referring to the master branch state or 2.8 tag, it is indeed pointing to a new feature (AIMS) which is enterprise level only, hence the error you are encountering on your part. The last release focused on delivering this capability and is currently unavailable as open source code. There is a possibility for that to be published in the near future but up to that point the best course of action for you would be to defer back to the 2.7 tag which should give you the same experience minus the aforementioned one. However, if you have an enterprise subscription please reach out to the support department at Alfresco so that we can further guide you along with building the app with this new feature.
