### ISSUE TITLE
Submittal to App Store after iOS9

### ISSUE THREAD

**Issue by frankbolviken** [Alfresco/alfresco-ios-app#594]
Finally been able to merge your latest iOS9 fixes into our own codebase. However, when we are going to deploy the app to App Store, we get 4 error messages as provided in the screenshot:

![screen shot 2015-09-29 at 15 18 40](https://cloud.githubusercontent.com/assets/688190/10165052/64d03b16-66bd-11e5-8c19-e0c255cd4d0c.png)

**Comment by mikeh** [comment]
Thanks for the bug report. I was expecting some issue around app submission due to the new rules about embedded frameworks and libraries. These don't seem too bad to resolve, as the resolution seems to be laid out in the error report. If you're successful resolving them, please do feel free to submit a pull request with the fixes. Thanks.
